Update the case test_backuptarget_available_during_engine_image_not_ready
longhorn/longhorn-tests pull request #1180
Opened 2022-11-15 00:49 UTC by roger-ryao

issue https://github.com/longhorn/longhorn/issues/4859

Signed-off-by: Roger Yao <roger.yao@suse.com>
(cherry picked from commit 40c4ae1e7a5be849899d84c5963efb8ab1252b58)

2022-11-15 03:21 UTC, khushboo-rancher approved these changes

2022-11-15 03:41 UTC, innobead commented
Wait to merge. @roger-ryao will revise this by cherry-pick from the PR to the master, also some minor changes are required.

2022-11-18 06:33 UTC, innobead requested changes
@roger-ryao should revise this by cherry-picking from the PR to the master, also some minor changes are required.

2022-11-24 14:24 UTC, c3y1huang approved these changes

2022-11-24 14:33 UTC, merged