Add test case test_csi_snapshot_snap_delete_csi_snapshot
longhorn/longhorn-tests pull request #1219
Opened 2022-12-07 05:57 UTC by chriscchien

Add test case test_csi_snapshot_snap_delete_csi_snapshot

Ref [4995](https://github.com/longhorn/longhorn/issues/4995)

Signed-off-by: Chris Chien <chris.chien@suse.com>

2022-12-08 04:14 UTC, c3y1huang requested changes

2022-12-08 04:14 UTC, c3y1huang commented on manager/integration/tests/test_csi_snapshotter.py
> +                                )
Indent looks weird.

2022-12-08 04:14 UTC, c3y1huang commented on manager/integration/tests/test_csi_snapshotter.py
> +    return deleted
Why not assert deleted?

2022-12-08 07:21 UTC, chriscchien commented on manager/integration/tests/test_csi_snapshotter.py
> +    return deleted
Updated`

2022-12-09 00:52 UTC, c3y1huang reviewed
It seems there are 3 cases here. Suggest separating them.

2022-12-09 00:52 UTC, c3y1huang commented on manager/integration/tests/test_csi_snapshotter.py
> +                                      core_api): # NOQA
Can you also fix the indents here?

2022-12-12 08:36 UTC, chriscchien commented on manager/integration/tests/test_csi_snapshotter.py
> +                                      core_api): # NOQA
Updated.

2022-12-22 06:19 UTC, c3y1huang requested changes
> Add test

Suggest updating the commit title to something more descriptive, ex: `Implement test_csi_snapshot_snap_delete_csi_snapshot cases`

2022-12-27 07:52 UTC, chriscchien commented
> > Add test
> 
> Suggest updating the commit title to something more descriptive, ex: `Implement test_csi_snapshot_snap_delete_csi_snapshot cases`

Updated!

2022-12-28 00:37 UTC, c3y1huang approved these changes

2022-12-28 00:38 UTC, merged

2023-02-23 01:30 UTC, yangchiu commented
@Mergifyio backport v1.4.x