Enlarge volume size in test_backup_status_for_unavailable_replicas
longhorn/longhorn-tests pull request #1246
Opened 2023-01-11 06:45 UTC by derekbit

Enlarge volume size for increasing backup time

Longhorn/longhorn#5189

Signed-off-by: Derek Su <derek.su@suse.com>

2023-01-11 06:51 UTC, derekbit commented
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2908

2023-01-12 02:26 UTC, shuo-wu approved these changes

2023-01-17 02:04 UTC, c3y1huang requested changes

2023-01-17 02:04 UTC, c3y1huang commented on manager/integration/tests/test_basic.py
> +    # Take snapshots4 without overlapping
```suggestion
    # Take snapshots without overlapping
```

2023-01-17 02:57 UTC, derekbit commented on manager/integration/tests/test_basic.py
> +    # Take snapshots4 without overlapping
Fixed. Thank you.

2023-01-17 03:09 UTC, c3y1huang approved these changes

2023-01-17 03:10 UTC, merged

2023-02-23 01:45 UTC, yangchiu commented
@Mergifyio backport v1.4.x