docs: Add manual test 'Test the trim related option update for old volumes'
longhorn/longhorn-tests pull request #1250
Opened 2023-01-13 04:05 UTC by shuo-wu

Longhorn/longhorn#5218

2023-01-16 08:29 UTC, innobead requested changes
LGTM, just ont typo.

2023-01-16 08:29 UTC, innobead commented on docs/content/manual/release-specific/v1.4.1/_index.md
> +title: v1.4.0
this should be `title: v1.4.1`

2023-01-17 03:11 UTC, c3y1huang approved these changes

2023-01-17 03:16 UTC, merged

2023-01-17 06:14 UTC, shuo-wu commented
https://github.com/Mergifyio backport v1.4.x