ci: check if new engine test images need to be published
longhorn/longhorn-tests pull request #1254
Opened 2023-02-20 01:05 UTC by yangchiu

ci: check if new engine test images need to be published

For https://github.com/longhorn/longhorn/issues/5400

Signed-off-by: Yang Chiu <yang.chiu@suse.com>

2023-02-20 17:07 UTC, innobead requested changes

2023-02-21 01:15 UTC, yangchiu commented on build_engine_test_images/run.sh
> +  if [[ $(docker manifest inspect "${upgrade_image}") != "" ]]; then
I make it run daily now: https://github.com/longhorn/infra/pull/117/files. Should we change it to weekly?

2023-02-21 01:27 UTC, innobead commented on build_engine_test_images/run.sh
> +  if [[ $(docker manifest inspect "${upgrade_image}") != "" ]]; then
Yeah weekly is good enough. Thanks!

2023-02-21 01:28 UTC, innobead approved these changes

2023-02-21 05:45 UTC, merged

2023-02-21 06:20 UTC, yangchiu commented on build_engine_test_images/run.sh
> +  if [[ $(docker manifest inspect "${upgrade_image}") != "" ]]; then
https://github.com/longhorn/infra/pull/117/files modified. It will only be triggered on Sunday 18:00.