feat(scheduling): add e2e skeleton for volume level soft anti affinity
longhorn/longhorn-tests pull request #1358
Opened 2023-05-12 07:21 UTC by ChanYiLin

ref: [longhorn/longhorn#5358](https://github.com/longhorn/longhorn/issues/5358)

2023-05-12 19:51 UTC, khushboo-rancher requested changes
If the manual cases are already covered in the automation test, no need to add the manual cases.

2023-05-16 07:31 UTC, ChanYiLin commented on manager/integration/tests/test_scheduling.py
> +    pass
Hi @khushboo-rancher 
We already have global soft_anti_affinity setting test
https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_scheduling.py#L95

- `def test_soft_anti_affinity_scheduling(client, volume_name)`: this is for **enable** global soft_anti_affinity setting
- `def test_hard_anti_affinity_scheduling(client, volume_name)`: this is for **disable** global soft_anti_affinity setting

In this PR, I added volume level test
- `def test_soft_anti_affinity_scheduling_volume_enable()`: **disable** global soft_anti_affinity setting, but **enable** volume soft_anti_affinity setting
- `def test_soft_anti_affinity_scheduling_volume_disable()`: **enable** global soft_anti_affinity setting, but **disable** volume soft_anti_affinity setting

thanks!

2023-05-16 07:43 UTC, ChanYiLin commented on docs/content/manual/functional-test-cases/scheduling.md
> +| EKS across zone scheduling - disable volume replicaZoneSoftAntiAffinity | **Prerequisite**:<br><br>*   EKS Cluster with 3 nodes across two AWS zones (zone#1, zone#2)<br><br>* Enable global replica
Fixed, thanks!

2023-05-18 10:48 UTC, innobead requested changes
`test-the-trim-related-option-update-for-old-volumes.md` file name is not right.

2023-05-18 10:52 UTC, innobead requested changes
LGTM, just one question.

2023-05-18 10:52 UTC, innobead commented on docs/content/manual/release-specific/v1.5.0/test-the-trim-related-option-update-for-old-volumes.md
> +*And* Upgrade Longhorn to the latest.
What does this mean?

2023-05-18 10:56 UTC, ChanYiLin commented on docs/content/manual/release-specific/v1.5.0/test-the-trim-related-option-update-for-old-volumes.md
> +*And* Upgrade Longhorn to the latest.
Fixed, thanks!

2023-05-18 10:57 UTC, ChanYiLin commented
> `test-the-trim-related-option-update-for-old-volumes.md` file name is not right.

fixed, thanks

2023-05-18 11:01 UTC, innobead approved these changes

2023-05-24 23:55 UTC, khushboo-rancher approved these changes

2023-05-24 23:55 UTC, merged