feat(backupstore): add azurite emulator
longhorn/longhorn-tests pull request #1382
Opened 2023-05-24 09:04 UTC by mantissahz

Add the Azurite manifest to start Azurite server for local testing

Ref: longhorn/longhorn#1309, https://github.com/longhorn/longhorn/issues/5994

2023-05-24 09:22 UTC, innobead commented
@mantissahz Can we add to longhorn/longhorn as well together with minio & nfs manifests for backupstore? Thanks.

2023-05-26 02:26 UTC, chriscchien approved these changes

2023-05-26 02:33 UTC, mantissahz commented
Added to longhorn/longhorn as well together with minio & nfs manifests for backupstore in this PR https://github.com/longhorn/longhorn/pull/6006

2023-05-28 17:01 UTC, innobead requested changes
Let's close this PR and create another issue to leverage the backup store deployment script from longhorn/longhorn instead of another duplicated manifest here.

2023-05-28 17:01 UTC, innobead commented on manager/integration/deploy/backupstores/azurite-backupstore.yaml
> +  name: azblob-secret
Why having two azblob-secret in different namespaces?

2023-05-29 03:17 UTC, mantissahz commented
Create an issue to follow up, We need to use manifests from longhorn/longhorn

2023-05-29 03:17 UTC, closed without merging