Revert PR-1336: Fix test_backup_failed_disable_auto_cleanup failure o…
longhorn/longhorn-tests pull request #1400
Opened 2023-06-03 14:26 UTC by roger-ryao

…n arm64

After executing the test case test_backup_failed_disable_auto_cleanup, we encountered an error specifically on the arm64 architecture. The longhorn-test pod crashed during the test.

Ref: https://github.com/longhorn/longhorn/issues/5461#issuecomment-1567633437

2023-06-04 08:13 UTC, yangchiu commented
Can you help to elaborate more on why/how does it happen?

2023-06-05 09:21 UTC, yangchiu requested changes
According to the original ticket https://github.com/longhorn/longhorn/issues/5461, the error message is
```
proxy error from 127.0.0.1:6443 while dialing 10.0.2.148:10250, code 503: 503 Service Unavailable
```
From my understanding, it means kube-apiserver is unable to communicate with kubelet, and it doesn't imply longhorn-test pod crashed.

Can you help to backport https://github.com/longhorn/longhorn-tests/pull/1242 and retest again?

2023-06-10 23:17 UTC, roger-ryao commented
> According to the original ticket [longhorn/longhorn#5461](https://github.com/longhorn/longhorn/issues/5461), the error message is
> 
> ```
> proxy error from 127.0.0.1:6443 while dialing 10.0.2.148:10250, code 503: 503 Service Unavailable
> ```
> 
> From my understanding, it means kube-apiserver is unable to communicate with kubelet, and it doesn't imply longhorn-test pod crashed.
> 
> Can you help to backport #1242 and retest again?

Hi @yangchiu :
    The backport #1242 has been retested and the results are available in https://github.com/longhorn/longhorn-tests/pull/1411#issuecomment-1585845205. We can ignore https://github.com/longhorn/longhorn-tests/pull/1400 and proceed with merging https://github.com/longhorn/longhorn-tests/pull/1411.

2023-06-11 07:15 UTC, roger-ryao commented
We can ignore https://github.com/longhorn/longhorn-tests/pull/1400 and proceed with merging https://github.com/longhorn/longhorn-tests/pull/1411.

2023-06-11 07:15 UTC, closed without merging