Add test skeleton of
longhorn/longhorn-tests pull request #1480
Opened 2023-07-28 08:07 UTC by chriscchien

Add test skeleton of
- `test_rwx_onine_expansion`
- `test_rwx_offine_expansion`

ref: [2181](https://github.com/longhorn/longhorn/issues/2181), [2484](https://github.com/longhorn/longhorn/issues/2484)

2023-07-31 01:31 UTC, yangchiu commented
Is it possible to correct the PR title?

2023-07-31 02:28 UTC, chriscchien commented
> Is it possible to correct the PR title?

Updated!

2023-08-02 01:34 UTC, yangchiu submitted a review, later dismissed
LGTM

2023-08-02 22:16 UTC, khushboo-rancher requested changes

2023-08-02 22:16 UTC, khushboo-rancher commented on manager/integration/tests/test_rwx.py
> +    """
Can we add one more step to write data of size 1.5 Gi, so that we know the expanded data is usable?

2023-08-02 22:16 UTC, khushboo-rancher commented on manager/integration/tests/test_rwx.py
> +    """
Same as above comment as writing 1.5 Gi in the expanded volume.

2023-08-08 05:39 UTC, innobead approved these changes

2023-08-08 18:42 UTC, khushboo-rancher approved these changes

2023-08-08 18:42 UTC, merged

2023-08-08 18:43 UTC, khushboo-rancher commented
@mergify backport v1.5.x v1.4.x