test skeleton: volume condition WaitForBackingImage
longhorn/longhorn-tests pull request #1551
Opened 2023-10-16 07:17 UTC by ChanYiLin

ref: [longhorn/longhorn#6615](https://github.com/longhorn/longhorn/issues/6615)

2023-10-22 03:59 UTC, yangchiu requested changes
@ChanYiLin The flake8 check failed. Could you help to fix it?

2023-12-14 07:03 UTC, ChanYiLin commented
Hi @yangchiu 
sorry for the late response, fixed, thanks!

2023-12-14 07:18 UTC, yangchiu approved these changes
LGTM

2023-12-19 20:59 UTC, khushboo-rancher approved these changes

2023-12-19 20:59 UTC, merged