test(negative): stress cpu/mem during volume attach detach
longhorn/longhorn-tests pull request #1567
Opened 2023-10-27 05:52 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/6951

2023-10-27 09:41 UTC, yangchiu requested changes
According to https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Negative+Testing `Phase 3` - `9. Increase CPU load on the nodes` and `10. High memory consumption`

It first inject the negative factor:
```
1. Deploy multiple apps on the cluster to increase the load of the CPU or on individual node increase load on CPU.
```
```
1. Deploy multiple apps on the cluster to increase memory consumption or on individual node increase the memory consumption.
```
And then run the for loop to do longhorn operations:
```
2. Perform the operations for a time period of 15-30 mins.
```

So probably in these test cases we inject high cpu/memory usage first, just like what we did in `control plane node network latency`, and then enter the for loop. And you don't even have to deal with duplicated stress pod.

2023-10-30 01:05 UTC, c3y1huang commented
> According to https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Negative+Testing `Phase 3` - `9. Increase CPU load on the nodes` and `10. High memory consumption`
> 
> It first inject the negative factor:
> 
> ```
> 1. Deploy multiple apps on the cluster to increase the load of the CPU or on individual node increase load on CPU.
> ```
> 
> ```
> 1. Deploy multiple apps on the cluster to increase memory consumption or on individual node increase the memory consumption.
> ```
> 
> And then run the for loop to do longhorn operations:
> 
> ```
> 2. Perform the operations for a time period of 15-30 mins.
> ```
> 
> So probably in these test cases we inject high cpu/memory usage first, just like what we did in `control plane node network latency`, and then enter the for loop. And you don't even have to deal with duplicated stress pod.

This is still a valid test case from my perspective. The user started off with an unstressed environment, and over time, there could be an increase in CPU and memory pressure. The scenario you've highlighted specifically tests the behavior of a pre-stressed environment, which I believe is also covered during the iteration of the test loop.

As for the duplicated stress pod, it's a general fix since we are keeping the LOOP_COUNT as an open parameter, so the timeout of the stress pod should reflect individual test runs and even the test run time. If not, it might terminate before the tests are completed. Do you have any concerns about that fix?

2023-11-03 05:55 UTC, yangchiu approved these changes
LGTM

2023-11-03 07:23 UTC, yangchiu approved these changes

2023-11-03 07:24 UTC, merged