Fix flaky test_volume_wait_for_backing_image_condition on ubuntu arm64
longhorn/longhorn-tests pull request #1669
Opened 2024-01-10 12:32 UTC by roger-ryao

Resolves issue longhorn/longhorn#7611 by fixing a flaky test case. 
The private image test results for different platforms are as follows:

1. sles amd64 : [link](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5951/)
2. sles arm64  : [link](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5952/)
3. ubuntu arm64  : [link](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5953/)

2024-01-23 02:21 UTC, yangchiu requested changes
I can't find the reason or context why we need to do these changes. Can you help to elaborate more?

Is it a timeout issue? Why both timeout and size modifications are needed? Only extending the timeout won't work?

2024-01-26 03:38 UTC, roger-ryao commented
> I can't find the reason or context why we need to do these changes. Can you help to elaborate more?
> 
> Is it a timeout issue? Why both timeout and size modifications are needed? Only extending the timeout won't work?

Hi @yangchiu 
     On `Ubuntu 22.04 arm64` , if we only modify the `TIMEOUT` without changing the SIZE, waiting for the backing image to complete takes around 350 to 390 seconds. However, if we reduce the SIZE by half, the time spent is approximately 200-250 seconds.
     
![Screenshot_20240126_112217](https://github.com/longhorn/longhorn-tests/assets/104337648/473702b9-7346-4385-8060-996790eba157)

2024-01-26 05:42 UTC, yangchiu approved these changes
LGTM

2024-01-26 05:45 UTC, merged

2024-01-29 00:51 UTC, roger-ryao commented
@mergify backport v1.6.x

2024-02-02 03:46 UTC, yangchiu commented
@roger-ryao Do `v1.5.x` and `v1.4.x` also need this fix?

2024-02-02 04:03 UTC, roger-ryao commented
> @roger-ryao Do `v1.5.x` and `v1.4.x` also need this fix?

After the merge of https://github.com/longhorn/longhorn-tests/pull/1662, we need to backport https://github.com/longhorn/longhorn-tests/pull/1669 to `v1.5.x`.

2024-02-02 04:04 UTC, roger-ryao commented
@mergify backport v1.5.x