feat(setting): lazy update for volume-related settings
longhorn/longhorn-tests pull request #1670
Opened 2024-01-11 12:50 UTC by mantissahz

Modify setting test cases for the new behavior.

Ref: longhorn/longhorn#7173

2024-01-11 13:21 UTC, innobead requested changes
Please also update the test description comment as well, if the behavior has been changed.

2024-01-11 13:21 UTC, innobead commented on manager/integration/tests/test_settings.py
> +    print("[James_DBG] len(expected_tolerations): {}, found: {}, \
Remove the personal log.

2024-01-11 14:21 UTC, mantissahz commented on manager/integration/tests/test_settings.py
> +    print("[James_DBG] len(expected_tolerations): {}, found: {}, \
Removed. Thanks.

2024-01-15 03:29 UTC, yangchiu approved these changes
LGTM

2024-01-15 06:34 UTC, innobead approved these changes

2024-01-15 06:34 UTC, merged

2024-01-15 10:19 UTC, yangchiu commented
@Mergify backport v1.6.x