test(manual) update Single replica node down
longhorn/longhorn-tests pull request #1913
Opened 2024-05-23 07:37 UTC by chriscchien

#### Which issue(s) this PR fixes:

Issue  longhorn/longhorn#8350

#### What this PR does / why we need it:

Add test scenario for volume and the only replica not on the same node.

#### Special notes for your reviewer:

N/A

#### Additional documentation or context

N/A

2024-05-23 23:54 UTC, khushboo-rancher requested changes
@chriscchien Have we covered all the scenarios in the automation?

2024-05-23 23:54 UTC, khushboo-rancher commented on docs/content/manual/pre-release/node-not-ready/node-down/single-replica-node-down.md
> +7. Power on the off node.
Typo: `Power on the node that is off` or `Power on the node`

2024-05-24 02:27 UTC, chriscchien commented
> @chriscchien Have we covered all the scenarios in the automation?

Updated and also update some type found by bot.
For the scenarios, yes I think automation covered all the scenarios.

2024-05-28 22:50 UTC, khushboo-rancher commented
>For the scenarios, yes I think automation covered all the scenarios.

It would be fine to remove the cases/file from manual test then :)

2024-05-29 02:07 UTC, chriscchien commented
> > For the scenarios, yes I think automation covered all the scenarios.
> 
> It would be fine to remove the cases/file from manual test then :)

Updated!

2024-05-29 17:12 UTC, khushboo-rancher approved these changes

2024-05-29 17:14 UTC, merged