fix: wait for backing image restoration finished before checking volume restoration
longhorn/longhorn-tests pull request #1916
Opened 2024-05-24 09:09 UTC by ChanYiLin

ref: https://github.com/longhorn/longhorn/issues/8515

We should check if BackingImage is restored and before checking volume is restored.
Because Volume needs to wait until BackingImage to restored.
It may timeout checking the status , because Volume is not finished yet.

2024-05-24 09:10 UTC, ChanYiLin commented
## Testing...

2024-05-27 00:53 UTC, c3y1huang submitted a review, later dismissed

2024-05-27 00:53 UTC, yangchiu requested changes

2024-05-27 00:53 UTC, yangchiu commented on manager/integration/tests/test_system_backup_restore.py
> +def test_system_backup_and_restore_volume_with_backingimage(client, core_api, volume_name, set_random_backupstore):  # NOQA
The test case can't be run. Got error:
```
_ ERROR at setup of test_system_backup_and_restore_volume_with_backingimage[s3] _
file /integration/tests/test_system_backup_restore.py, line 125
  @pytest.mark.system_backup_restore   # NOQA
  def test_system_backup_and_restore_volume_with_backingimage(client, core_api, volume_name, set_random_backupstore):  # NOQA
E       fixture 'core_api' not found
```

2024-05-27 09:10 UTC, ChanYiLin commented on manager/integration/tests/test_system_backup_restore.py
> +def test_system_backup_and_restore_volume_with_backingimage(client, core_api, volume_name, set_random_backupstore):  # NOQA
fixed, thanks

2024-05-27 09:12 UTC, ChanYiLin commented
Hi @yangchiu 
I have fixed the comment
While testing, I found there is a bug which make the test flaky
I have created the PR to fix it: https://github.com/longhorn/longhorn-manager/pull/2823

You can wait for the fix PR to be merged, and test it and merge it after.

2024-05-31 03:24 UTC, yangchiu commented
Merge this first to reveal the issue of https://github.com/longhorn/longhorn-manager/pull/2823.

2024-05-31 03:24 UTC, merged

2024-05-31 06:20 UTC, ChanYiLin commented
Hi @yangchiu 
We can first verified the system restore with BackingImage in this issue and close the issue first:　https://github.com/longhorn/longhorn/issues/8515


Then for e2e flaky issue because of backup failed 
The fix has changed to this implementation: https://github.com/longhorn/longhorn-manager/pull/2835
We can use this issue to verified: https://github.com/longhorn/longhorn/issues/8650

Thanks!