test(robot): extend negative test cases to include v2 data engine
longhorn/longhorn-tests pull request #2033
Opened 2024-07-31 23:50 UTC by yangchiu

#### Which issue(s) this PR fixes:

Issue N/A

#### What this PR does / why we need it:

extend negative test cases to include v2 data engine

#### Special notes for your reviewer:

#### Additional documentation or context

2024-08-02 04:21 UTC, yangchiu commented
@roger-ryao @chriscchien Please help merge this to enhance the test coverage for v2 volume. Thank you!

2024-08-04 13:26 UTC, yangchiu commented
https://github.com/longhorn/longhorn/issues/9171#issuecomment-2267541293

> The is a known issue. v2 volume doesn't support auto-salvage. The feature will be implemented in v1.8.0.

v2 volume is not possible to pass negative tests. Defer this PR for now.

2024-08-06 20:02 UTC, khushboo-rancher requested changes
nit: In general, if we can add brief description of test cases that will be helpful as the test cases are becoming bigger. 
e.g.
```
This test validates the cluster's stability and recovery during heavy data writing operations across multiple workloads with different storage configurations. The test creates:

3 RWO volumes with the following storage classes:
 a. longhorn-test
 b. strict-local
 c. strict-local (for statefulset)
3 RWX volumes with the following storage classes:
 a. longhorn-test
 b. nfs-4-2
 c. nfs-4-2 (for statefulset)
 d. nfs-hard-mount
 e. nfs-soft-mount
Deployments and statefulsets are created using these volumes, and data is continuously written to them. The cluster is then restarted, and the test verifies that all workloads resume correctly and data integrity is maintained post-restart.
```

2024-08-07 00:42 UTC, yangchiu commented on e2e/libs/volume/crd.py
> +            time.sleep(self.retry_count)
Failing the test case doesn't help investigate and debug the issue. It only causes developers to spend more time reproducing it.

2024-08-07 00:54 UTC, yangchiu commented on e2e/keywords/network.resource
> +    [Arguments]    @{args}
Yes, we can figure out a standard way to document the parameters and usage of each keyword.

2024-08-07 00:56 UTC, yangchiu commented on e2e/tests/cluster_restart.robot
> +    And Create storageclass nfs-soft-mount with    nfsOptions=soft,timeo=250,retrans=5    dataEngine=${DATA_ENGINE}
I'm not sure about this. The build-in storage class don't have `sc` prefix as well:

```
$ kubectl get sc
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  16m
longhorn (default)     driver.longhorn.io      Delete          Immediate              true                   11m
longhorn-static        driver.longhorn.io      Delete          Immediate              true                   11m
```

2024-08-07 00:58 UTC, yangchiu commented on e2e/tests/cluster_restart.robot
>  Restart Cluster While Workload Heavy Writing
Sure! I'll add descriptions for each test case in the next PR. Thank you!

2024-08-07 01:27 UTC, yangchiu commented on e2e/libs/keywords/network_keywords.py
> +        await disconnect_node_network(node_name, int(disconnection_time_in_sec))
Good catch! The `await` has been removed. Thank you!

2024-08-07 01:29 UTC, yangchiu commented
> nit: In general, if we can add brief description of test cases that will be helpful as the test cases are becoming bigger. 

Created https://github.com/longhorn/longhorn/issues/9204 for it.

2024-08-07 22:19 UTC, khushboo-rancher commented on e2e/libs/volume/crd.py
> +            time.sleep(self.retry_count)
If checksum doesn't match, will the test case still pass or person implementing the test case will have to take care of it?
Btw, the message in the assert won't help?

2024-08-08 00:38 UTC, yangchiu commented on e2e/libs/volume/crd.py
> +            time.sleep(self.retry_count)
Good catch! I added the assertion back after the sleep. Thank you!

2024-08-09 20:12 UTC, khushboo-rancher approved these changes

2024-08-09 20:12 UTC, merged