ci: github action for syncing manual test cases with qase
longhorn/longhorn-tests pull request #2066
Opened 2024-08-21 02:42 UTC by yangchiu

#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/7412

#### What this PR does / why we need it:

github action for syncing manual test cases with qase

#### Special notes for your reviewer:

#### Additional documentation or context

2024-08-21 22:52 UTC, khushboo-rancher requested changes
1. Can we separate the logic from yaml file, WDYT?
2. Have we considered deleting any manual test case PR?

2024-08-22 04:09 UTC, yangchiu commented
Require https://github.com/longhorn/bot/pull/29

2024-08-22 04:10 UTC, yangchiu commented
> 1. Can we separate the logic from yaml file, WDYT?

Moved logic to longhorn/bot repo: https://github.com/longhorn/bot/pull/29

> 
>     2. Have we considered deleting any manual test case PR?

Dealt with deleting manual test case in https://github.com/longhorn/bot/pull/29/files#diff-f3c3277164b78a0fc1709361a62f4c9f655edc70477890844e6aff74a705f37fR112

2024-08-27 22:06 UTC, khushboo-rancher approved these changes

2024-08-27 22:07 UTC, merged