Add manual test steps for Prometheus Support.
longhorn/longhorn-tests pull request #416
Opened 2020-09-22 23:23 UTC by khushboo-rancher

https://github.com/longhorn/longhorn/issues/1180

Signed-off-by: khushboo-rancher <khushboo@rancher.com>

2020-10-01 21:55 UTC, yasker approved these changes

2020-10-01 22:04 UTC, PhanLe1010 requested changes
Left a small comment.  Otherwise, LGTM

2020-10-01 22:04 UTC, PhanLe1010 commented on docs/content/manual/release-specific/v1.1.0/prometheus_support.md
> +6. Attach a volume. Detach the volume. Verify that the volume's information is reported by at most 1 longhorn-manager at any time.
Attach a volume. Detach the volume then attach it to a different node. Verify that the volume's information is reported by at most 1 longhorn-manager at any time.

2020-10-01 22:10 UTC, PhanLe1010 commented
LGTM

2020-10-02 01:25 UTC, PhanLe1010 approved these changes

2020-10-02 01:27 UTC, merged