doc: Add a manual test for the node cleanup feature
longhorn/longhorn-tests pull request #435
Opened 2020-10-16 12:19 UTC by shuo-wu

longhorn/longhorn#1232

2020-10-16 16:43 UTC, yasker approved these changes

2020-10-16 17:07 UTC, khushboo-rancher commented
LGTM.

However, I think we can have more test scenarios like 
1. Multiple nodes removal.
2. Removing the node when in down/disable state and make sure the corresponding Kubernetes node object is deleted.

2020-10-16 17:10 UTC, yasker requested changes
Let's move this to the `pre-release` test instead of `v1.1.0` test.

And we should add the test steps from https://github.com/longhorn/longhorn/issues/1232 too.

2020-10-17 03:16 UTC, shuo-wu commented
The test doc is updated:
1. Scale the existing test case to multiple-node scenarios
2. Add the reproduce step of longhorn/longhorn#1232 as the 2nd test case.

2020-10-17 04:41 UTC, yasker approved these changes

2020-10-17 04:41 UTC, merged