Implement test_replica_rebuild_per_volume_limit
longhorn/longhorn-tests pull request #487
Opened 2020-11-20 09:15 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/307

2020-11-20 18:18 UTC, yasker requested changes

2020-11-20 18:18 UTC, yasker commented on manager/integration/tests/common.py
> +            assert wo_count <= VOLUME_REPLICA_WO_LIMIT
Should put this outside of the loop.

2020-11-23 02:10 UTC, c3y1huang commented on manager/integration/tests/common.py
> +            assert wo_count <= VOLUME_REPLICA_WO_LIMIT
Addressed.

2020-11-23 17:27 UTC, yasker approved these changes

2020-11-23 17:27 UTC, merged