add test skeleton for feature `Automatically upgrade volumes' engine to the default engine image after upgrading Longhorn`
longhorn/longhorn-tests pull request #522
Opened 2021-01-23 00:34 UTC by PhanLe1010

longhorn/longhorn#2152

2021-01-25 04:50 UTC, shuo-wu requested changes
We can add more tests for the setting:
1. The engine upgrade API is disabled when the setting is enabled
2. The upgrade shouldn't start when the volume is degraded.
3. Offline upgrade (you can create more volumes but do not attach them in case1)

2021-01-25 19:23 UTC, PhanLe1010 commented
> The engine upgrade API is disabled when the setting is enabled

We test it here https://github.com/longhorn/longhorn-tests/blob/b0d73df12fce9633112aa26d8c1b0c1b158158e4/manager/integration/tests/test_engine_upgrade.py#L724

> The upgrade shouldn't start when the volume is degraded.

I think it is ok to upgrade the degraded volumes

> Offline upgrade (you can create more volumes but do not attach them in case1)

We already has 5 detached volumes in case 1, do we need to create more?

2021-01-26 05:02 UTC, shuo-wu commented
Oh sorry for missing some steps. No, 5 detached volumes are enough.

2021-01-27 05:16 UTC, shuo-wu submitted a review, later dismissed
In general LGTM

2021-01-27 05:16 UTC, shuo-wu commented on manager/integration/tests/test_engine_upgrade.py
> +    Case 2: Dr volume
`DR volume`

2021-01-27 06:06 UTC, PhanLe1010 commented on manager/integration/tests/test_engine_upgrade.py
> +    Case 2: Dr volume
Thank you. Fixed

2021-01-27 10:12 UTC, shuo-wu approved these changes

2021-01-28 15:41 UTC, merged