Add test_replica_failure_during_attaching test
longhorn/longhorn-tests pull request #523
Opened 2021-01-26 10:21 UTC by khushboo-rancher

https://github.com/longhorn/longhorn/issues/1999

2021-01-27 05:09 UTC, shuo-wu requested changes
The test steps need to be updated:
```
10. Wait for the replenishment interval.
11. Enable the default disk for the host node.	
12. Wait for volume2 to become Healthy. 
        --> Verify the failed replica using the extra disk will not be reused. Instead, a new replica will be rebuilt in the default disk enabled in step11
13. Verify data content and r/w capability for volume2.
```

2021-02-08 23:21 UTC, meldafrawi commented on manager/integration/tests/test_ha.py
> +    volume_name_2 = volume_name_1 + '-2'
fixed

2021-02-08 23:21 UTC, meldafrawi commented on manager/integration/tests/test_ha.py
> +    common.lazy_umount_disk(mount_path)
fixed

2021-02-08 23:23 UTC, meldafrawi commented
@shuo-wu I've fixed all your comments and added them to a different PR https://github.com/longhorn/longhorn-tests/pull/531

@khushboo-rancher Great job, Thank you.

2021-02-08 23:24 UTC, meldafrawi commented
Closing this PR in favor to https://github.com/longhorn/longhorn-tests/pull/531

2021-02-08 23:24 UTC, closed without merging