E2E tests for volume live migration
longhorn/longhorn-tests pull request #543
Opened 2021-03-01 20:19 UTC by joshimoo

longhorn/longhorn#2127

2021-03-03 04:35 UTC, shuo-wu requested changes

2021-03-03 04:35 UTC, shuo-wu commented on manager/integration/tests/test_migration.py
>  def migration_confirm_test(clients, volume_name, base_image=""):  # NOQA
Need the test skeleton. Same below

2021-03-03 04:35 UTC, shuo-wu commented on manager/integration/tests/test_migration.py
> +def setup_migration_test(clients, volume_name, base_image=""): # NOQA
Rename `base_image` to `backing_image`

2021-03-03 04:35 UTC, shuo-wu commented on manager/integration/tests/test_migration.py
> +                                  baseImage=base_image,
Rename `base_image` to `backing_image`

2021-03-03 04:35 UTC, shuo-wu commented on manager/integration/tests/test_migration.py
>      assert "migration is not ready" in str(e.value)
Is this for checking a transient state? If YES, we need to remove this. Same below

2021-03-05 02:54 UTC, shuo-wu requested changes
The content LGTM. But the modification based on the review should be in the 1st commit.

2021-03-05 12:03 UTC, joshimoo commented
squashed the commits.

2021-03-05 12:26 UTC, shuo-wu approved these changes

2021-03-09 20:23 UTC, merged