add get_engine_image_status_value
longhorn/longhorn-tests pull request #553
Opened 2021-03-10 20:44 UTC by meldafrawi

Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

Ref: https://github.com/longhorn/longhorn/issues/2321

2021-03-11 02:52 UTC, c3y1huang requested changes

2021-03-11 02:52 UTC, c3y1huang commented on manager/integration/tests/common.py
> +        setting_name = setting.definition.name
I think this should be `setting.name`.

2021-03-11 02:56 UTC, shuo-wu commented on manager/integration/tests/common.py
> +        setting_name = setting.definition.name
The setting data is like this:
```
{
  "actions": { },
  "definition": {
    "category": "general",
    "default": "false",
    "description": "By default, Longhorn will block `kubectl drain` action on a node if the node contains the last healthy 
  replica of a volume.\n\nIf this setting is enabled, Longhorn will **not** block `kubectl drain` action on a node even if 
  the node contains the last healthy replica of a volume.",
    "displayName": "Allow Node Drain with the Last Healthy Replica",
    "readOnly": false,
    "required": true,
    "type": "bool",
  },
  "id": "allow-node-drain-with-last-healthy-replica",
  "name": "allow-node-drain-with-last-healthy-replica",
  "timestamp": "2021-03-11T02:44:32.632940164Z",
  "type": "setting",
  "value": "false",
},
```

2021-03-11 21:22 UTC, meldafrawi commented on manager/integration/tests/common.py
> +        setting_name = setting.definition.name
Fixed, Thanks

2021-03-12 00:07 UTC, c3y1huang approved these changes
LGTM

2021-03-12 07:33 UTC, innobead approved these changes

2021-03-12 07:34 UTC, merged