integration: Fix test_instance_manager_cpu_reservation
longhorn/longhorn-tests pull request #555
Opened 2021-03-11 12:16 UTC by shuo-wu

2021-03-11 12:26 UTC, shuo-wu commented
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/60/

2021-03-12 00:16 UTC, c3y1huang commented
Ref https://github.com/longhorn/longhorn/issues/2325

2021-03-12 02:26 UTC, c3y1huang requested changes
Just some wordings and indent need to resolve. Others LGTM.

2021-03-12 02:26 UTC, c3y1huang commented on manager/integration/tests/test_settings.py
> +    2. Pick up nodeA, set `node.engineManagerCPURequest` and
```suggestion
    2. Pick up node 1, set `node.engineManagerCPURequest` and
```

2021-03-12 02:26 UTC, c3y1huang commented on manager/integration/tests/test_settings.py
>      5. Set the fields on node1 to 0.
```suggestion
    5. Set the fields on node 1 to 0.
```

2021-03-12 02:26 UTC, c3y1huang commented on manager/integration/tests/test_settings.py
> +       Then wait for all IM pods except for the pods on nodeA restarting.
```suggestion
       Then wait for all IM pods except for the pods on node 1 restarting.
```

2021-03-12 02:26 UTC, c3y1huang commented on manager/integration/tests/test_settings.py
> +       --> All IM pods except for the pod on nodeA will be restarted without
```suggestion
       --> All IM pods except for the pod on node 1 will be restarted without
```

2021-03-12 02:26 UTC, c3y1huang commented on manager/integration/tests/test_settings.py
> +        assert "the sum should not be smaller than 0% or greater than 40%" in \
```suggestion
    assert "the sum should not be smaller than 0% or greater than 40%" in \
```

2021-03-12 05:29 UTC, innobead submitted a review, later dismissed
LGTM (btw @c3y1huang  has some comments to resolve).

I think different test cases combined in one test function are not easy for tracing although this is the current implementation already, also I know another reason is we want to leverage the function description for the test case description. 

We can revisit all test cases later to enhance a bit w/ more logging and comments for easy maintenance.

2021-03-12 13:28 UTC, shuo-wu commented
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/73/

2021-03-15 03:12 UTC, c3y1huang approved these changes

2021-03-15 03:19 UTC, merged