Add test cases for engine not deployed fully
longhorn/longhorn-tests pull request #589
Opened 2021-04-08 15:20 UTC by khushboo-rancher

https://github.com/longhorn/longhorn/issues/2081

Signed-off-by: khushboo-rancher <fnu.khushboo@suse.com>

2021-04-08 16:37 UTC, innobead requested changes
LGTM, some minor changes required

2021-04-08 16:37 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 4: Test replicas scheduling when engine image DaemonSet is not fully deployed
```suggestion
### Case 4: Test replicas scheduling when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-08 16:37 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 5: Test Longhorn upgrade when engine image DaemonSet is not fully deployed
```suggestion
### Case 5: Test Longhorn upgrade when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-08 16:37 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 6: Test `auto upgrade engine` feature when engine image DaemonSet is not fully deployed
```suggestion
### Case 6: Test `auto upgrade engine` feature when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-08 16:37 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 7: Test `auto attach volume for recurring backup job` feature when engine image DaemonSet is not fully deployed
```suggestion
### Case 7: Test `auto attach volume for recurring backup job` feature when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-08 16:37 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 8: Test DR, restoring, expanding volumes  when engine image DaemonSet is not fully deployed
```suggestion
### Case 8: Test DR, restoring, expanding volumes  when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-08 16:37 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 9: Test reusing failed replica when engine image DaemonSet is not fully deployed
```suggestion
### Case 9: Test reusing failed replica when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-08 20:25 UTC, khushboo-rancher commented
Added the suggestions.

2021-04-09 06:31 UTC, innobead requested changes

2021-04-09 06:31 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 1: Test volume operations when engine image DaemonSet is miss scheduled
```suggestion
### Case 1: Test volume operations when some of the engine image DaemonSet pods are miss scheduled 
```

2021-04-09 06:31 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 2: Test volume operations engine image DaemonSet is not fully deployed
```suggestion
### Case 2: Test volume operations when some of engine image DaemonSet pods are not fully deployed
```

2021-04-09 06:31 UTC, innobead commented on docs/content/manual/release-specific/v1.1.1/partial-engine-deployment.md
> +### Case 3: Test engine upgrade when engine image DaemonSet is not fully deployed
```suggestion
### Case 3: Test engine upgrade when some of the engine image DaemonSet pods are not fully deployed
```

2021-04-09 06:32 UTC, innobead approved these changes

2021-04-09 06:33 UTC, merged