Add manual test frontend payload when no resource updated
longhorn/longhorn-tests pull request #618
Opened 2021-05-31 10:53 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/2646
https://github.com/longhorn/longhorn/issues/2591

2021-06-01 18:21 UTC, khushboo-rancher requested changes
I think the test addition in v1.1.2 should be sufficient, same tests need not be added to v1.20

2021-06-02 03:02 UTC, c3y1huang commented
> I think the test addition in v1.1.2 should be sufficient, same tests need not be added to v1.20

Addressed, manual test commit dropped for v1.2.0. Currently keeping the commit for the folder, let me know if want to have that dropped too.

2021-06-02 18:26 UTC, khushboo-rancher approved these changes
LGTM

2021-06-03 02:15 UTC, innobead approved these changes

2021-06-03 02:15 UTC, merged