Add a new test test_backuptarget_available_during_engine_image_not_ready
longhorn/longhorn-tests pull request #706
Opened 2021-09-13 01:44 UTC by jenting

#### Proposal Change

Add a new test `test_backuptarget_available_during_engine_image_not_ready` to verify configures the backup target setting during the default engine image is not ready.

#### Issues

Longhorn 2960

2021-09-13 03:16 UTC, jenting commented
Test results https://ci.longhorn.io/job/private/job/longhorn-tests-regression/457/testReport/tests/test_basic/

2021-09-13 03:34 UTC, shuo-wu requested changes

2021-09-13 03:34 UTC, shuo-wu commented on manager/integration/tests/test_basic.py
> +            time.sleep(1)  # Wait for the engine image Pods be deleted
Use a retry loop to validate the default engine image becoming not-ready.

2021-09-13 03:34 UTC, shuo-wu commented on manager/integration/tests/test_basic.py
> +                    'BackupTarget status.available should be True')
Use a retry loop to validate the backup target becoming available. Similar below

2021-09-13 03:34 UTC, shuo-wu commented on manager/integration/tests/test_basic.py
> +            set_backupstore_credential_secret(client, cred_secret)
Make sure the backup target is unavailable here.

2021-09-15 06:20 UTC, shuo-wu approved these changes
Based on the current manager PR, this LGTM. But we need to re-check this if there is any modification introduced in the manager PR.

2021-09-15 09:31 UTC, innobead approved these changes
LGTM

2021-09-15 19:19 UTC, khushboo-rancher approved these changes
LGTM

2021-09-16 06:04 UTC, shuo-wu commented
This test is good to go after resolving the conflict.

2021-09-16 06:12 UTC, shuo-wu approved these changes

2021-09-16 06:12 UTC, merged

2021-09-16 06:16 UTC, innobead commented
@jenting Please backport to 1.2.x.