Separate s3 and nfs test
longhorn/longhorn-tests pull request #707
Opened 2021-09-13 16:39 UTC by khushboo-rancher

https://github.com/longhorn/longhorn/issues/2999

Signed-off-by: Khushboo <fnu.khushboo@suse.com>

2021-09-15 09:15 UTC, innobead requested changes
This is an easy way to separate the test execution w/ different backup stores. 

But I would expect if we can leverage the same scripts, Jenkinsfile, manifests, etc w/ some conditional check inside to have an adaptive run when giving different test runtime configurations. This will be much better for test setup management. WDYT?

2021-09-30 23:06 UTC, khushboo-rancher commented
@innobead I have made the changes as per suggestion. Could you please have a look.
cc: @meldafrawi

2021-10-01 09:19 UTC, innobead requested changes
LGTM, just a format suggestion to resolve.

2021-10-01 09:19 UTC, innobead commented on test_framework/scripts/longhorn-setup.sh
> +	fi
```suggestion
	if [[ $BACKUP_STORE_TYPE = "nfs" ]]; then
	  LONGHORN_TESTS_MANIFEST_FILE_PATH="${LONGHORH_TESTS_REPO_BASEDIR}/manager/integration/deploy/test_nfs.yaml"
	elif [[ $BACKUP_STORE_TYPE = "s3" ]]; then
	  LONGHORN_TESTS_MANIFEST_FILE_PATH="${LONGHORH_TESTS_REPO_BASEDIR}/manager/integration/deploy/test_s3.yaml"
	else
			LONGHORN_TESTS_MANIFEST_FILE_PATH="${LONGHORH_TESTS_REPO_BASEDIR}/manager/integration/deploy/test.yaml"
	fi
```

2021-10-01 09:19 UTC, innobead commented on test_framework/scripts/longhorn-setup.sh
> +	fi
```suggestion
	if [[ $BACKUP_STORE_TYPE = "nfs" ]]; then
	  LONGHORN_TESTS_MANIFEST_FILE_PATH="${LONGHORH_TESTS_REPO_BASEDIR}/manager/integration/deploy/test_nfs.yaml"
	elif [[ $BACKUP_STORE_TYPE = "s3" ]]; then
		LONGHORN_TESTS_MANIFEST_FILE_PATH="${LONGHORH_TESTS_REPO_BASEDIR}/manager/integration/deploy/test_s3.yaml"
	else
	  LONGHORN_TESTS_MANIFEST_FILE_PATH="${LONGHORH_TESTS_REPO_BASEDIR}/manager/integration/deploy/test.yaml"
	fi
```

2021-10-05 00:40 UTC, innobead approved these changes
LGTM

2021-10-05 00:40 UTC, merged