Flakiness test case : test_node_config_annotation_missing (test_node.py)
longhorn/longhorn-tests pull request #736
Opened 2021-10-08 09:04 UTC by chriscchien

This test case is flakiness because during testing run time , instance-manager-r restarted and in teardown step check instance-manager-r running well.

Sometimes, test completed and entering teardown steps, the instance-manager-r still in terminating then got a new name, but teardown still use old name(terminated one), script got api response code 500 and direct raise error.

So I added try - except section in wait_for_all_instance_manager_running(), let the retry mechanism can still work.

2021-10-12 01:39 UTC, jenting requested changes
Could you please change your signoff-by email address to use the suse.com email? Thank u.

2021-10-13 00:31 UTC, chanow816 commented on manager/integration/tests/common.py
> +            continue
Yes If I add time.sleep(15) before `for im in instance_managers:`, all instance-manager-r will ready for next steps

2021-10-13 22:41 UTC, jenting commented on manager/integration/tests/common.py
> +        except ApiException:
If we change to catch the `ApiException` error under function `wait_for_instance_manager_desire_state`, would it be better?

2021-10-14 02:21 UTC, jenting commented on manager/integration/tests/common.py
> +        except ApiException:
We should update the `node_to_engine_manager_map` since it'd change for the newly created instance/replica instance manager Pods name.

2021-10-18 09:05 UTC, merged