Recurring job start just after minute start
longhorn/longhorn-tests pull request #794
Opened 2021-11-12 07:07 UTC by chanow816

Signed-off-by: Chris Chien <chris.chien@suse.com>
From https://github.com/longhorn/longhorn/issues/3233, we have some flaky recurring job cases in daily run.

Most cases fail reason was timing issue. Longhorn recurring job started at  beginning of a minute, but our test cases will set recurring job directly (maybe at 55th second), then do some test steps then do sleep **whole** minute and check result in the end

Test steps after set recurring job will take minutes(especially backup target was s3), sleep whole minute not accurate, so I modified `create_recurring_jobs` and reduce sleep time in test cases.

2021-11-12 13:42 UTC, jenting commented
>  Longhorn recurring job started at beginning of a minute, but our test cases will set recurring job directly 

Nice catch!

2021-11-12 13:46 UTC, innobead requested changes

2021-11-12 13:46 UTC, innobead commented on manager/integration/tests/common.py
> +    for i in range(60):
Why not just wait for the rest of seconds in a minute?

Something like

```python
time.sleep(60 - datetime.utcnow().second)
```

2021-11-12 13:46 UTC, innobead commented on manager/integration/tests/test_recurring_job.py
> +    time.sleep(140)  # 2.5 minutes - 10 secends
If you already made the change in create_recurring_jobs, why need to change the sleep time? (including the all changes in this module)

2021-11-12 13:47 UTC, innobead commented
> > Longhorn recurring job started at beginning of a minute, but our test cases will set recurring job directly
> 
> Nice catch!

Indeed 👍

2021-11-16 03:07 UTC, chanow816 commented
Hi @innobead ,

The most flaky scenario was we set recurring job retain count to 2, scheduled each minute, after 1 whole minute passed we check backup should equal 1, however somehow the back count equal 2 (Because we checked too late, second retain already completed), this caused by:
- Actions between set recurring job and check backup count need time.
- We set recurring at end of minutes , like 55th second 

So I try to set recurrent job just after minute start and reduce sleep time in each flaky case, thank you.

2021-11-16 03:16 UTC, innobead approved these changes

2021-11-16 03:16 UTC, merged

2021-11-16 03:17 UTC, innobead commented
@chanow816 plz backport to 1.2.x and 1.1.3. Thanks.