Fix asserting message in test_recurring_jobs_maximum_retain
longhorn/longhorn-tests pull request #933
Opened 2022-04-07 10:39 UTC by kaxing

The current case will fail with longhorn-manager v1.3.0-dev(master branch), due to the introduction of webhook.
Adjusting the assertion string to make it recognize the error message.

---
pytest output for the reference:
```
_______________________________________________________________________ test_recurring_jobs_maximum_retain ________________________________________________________________________

client = <longhorn.Client object at 0x7f7de8274d90>, core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f7de8475a00>, volume_name = 'longhorn-testvol-25ptih'

    def test_recurring_jobs_maximum_retain(client, core_api, volume_name): # NOQA
        """
        Scenario: test recurring jobs' maximum retain

        Given set a recurring job retain to 51.

        When create recurring job.
        Then should fail.

        When set recurring job retain to 50.
        And create recurring job.
        Then recurring job created with retain equals to 50.

        When update recurring job retain to 51.
        Then should fail.
        """
        # set max total number of retain to exceed 50
        recurring_jobs = {
            RECURRING_JOB_NAME: {
                TASK: BACKUP,
                GROUPS: [],
                CRON: SCHEDULE_1MIN,
                RETAIN: 51,
                CONCURRENCY: 1,
                LABELS: {},
            },
        }
        with pytest.raises(Exception) as e:
            create_recurring_jobs(client, recurring_jobs)
>       assert "spec.retain in body should be less than or equal to 50".upper()\
            in str(e.value).upper()
E       assert 'SPEC.RETAIN IN BODY SHOULD BE LESS THAN OR EQUAL TO 50' in '(APIERROR(...), \'500 : UNABLE TO CREATE RECURRING JOB RECURRING-TEST: ADMISSION WEBHOOK "VALIDATOR.LONGHORN.IO" DENI...IDATOR.LONGHORN.IO" DENIED THE REQUEST: RETAIN IN BODY SHOULD BE LESS THAN OR EQUAL TO 50\\\', \\\'STATUS\\\': 500}\')'
E        +  where 'SPEC.RETAIN IN BODY SHOULD BE LESS THAN OR EQUAL TO 50' = <built-in method upper of str object at 0x7f7de8592b90>()
E        +    where <built-in method upper of str object at 0x7f7de8592b90> = 'spec.retain in body should be less than or equal to 50'.upper
E        +  and   '(APIERROR(...), \'500 : UNABLE TO CREATE RECURRING JOB RECURRING-TEST: ADMISSION WEBHOOK "VALIDATOR.LONGHORN.IO" DENI...IDATOR.LONGHORN.IO" DENIED THE REQUEST: RETAIN IN BODY SHOULD BE LESS THAN OR EQUAL TO 50\\\', \\\'STATUS\\\': 500}\')' = <built-in method upper of str object at 0x55c94cae5440>()
E        +    where <built-in method upper of str object at 0x55c94cae5440> = '(ApiError(...), \'500 : unable to create recurring job recurring-test: admission webhook "validator.longhorn.io" deni...idator.longhorn.io" denied the request: retain in body should be less than or equal to 50\\\', \\\'status\\\': 500}\')'.upper
E        +      where '(ApiError(...), \'500 : unable to create recurring job recurring-test: admission webhook "validator.longhorn.io" deni...idator.longhorn.io" denied the request: retain in body should be less than or equal to 50\\\', \\\'status\\\': 500}\')' = str(ApiError(ApiError(...), '500 : unable to create recurring job recurring-test: admission webhook "validator.longhorn.io...ook "validator.longhorn.io" denied the request: retain in body should be less than or equal to 50\', \'status\': 500}'))
E        +        where ApiError(ApiError(...), '500 : unable to create recurring job recurring-test: admission webhook "validator.longhorn.io...ook "validator.longhorn.io" denied the request: retain in body should be less than or equal to 50\', \'status\': 500}') = <ExceptionInfo ApiError(ApiError(...), '500 : unable to create recurring job recurring-test: admission webhook "valida...dator.longhorn.io" denied the request: retain in body should be less than or equal to 50\', \'status\': 500}') tblen=7>.value

test_recurring_job.py:604: AssertionError
```

2022-04-07 13:14 UTC, innobead reviewed
I can't see what's the difference after this change. 

What's the actual problem u want to fix?

2022-04-08 02:03 UTC, kaxing commented
When testing the 51 retain count, the error message for verification `SPEC.RETAIN IN BODY SHOULD BE LESS THAN OR EQUAL TO 50` is slightly different with v1.3.0-dev, where it begin with `validator.longhorn.io" denied the request: retain in body ...`

2022-04-08 08:16 UTC, innobead requested changes

2022-04-08 08:16 UTC, innobead commented on manager/integration/tests/test_recurring_job.py
> +        "retain" + " in body should be less than or equal to " + "50"
```suggestion
    validator_error = "retain in body should be less than or equal to 50"
```

2022-04-08 10:06 UTC, innobead approved these changes

2022-04-08 10:06 UTC, merged