integration: add test cases for setting update via configmap
longhorn/longhorn-tests pull request #969
Opened 2022-05-25 00:58 UTC by derekbit

longhorn/longhorn#2570

Signed-off-by: Derek Su <derek.su@suse.com>

2022-05-25 06:38 UTC, kaxing submitted a review, later dismissed
Looking good!

2022-05-27 05:44 UTC, cchien816 approved these changes
LGTM

2022-06-01 04:58 UTC, cchien816 commented
e2e result on v1.3.0-rc2 : [Pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1438/testReport/tests/test_settings/)

2022-07-21 04:22 UTC, innobead requested changes
LGTM, just one comment needed to resolve.

2022-07-26 07:58 UTC, derekbit commented on manager/integration/tests/test_settings.py
> +    num_threads = 50
I remove the concurrent test from e2e, because it should be at scaling test suite.

2022-07-26 08:10 UTC, innobead approved these changes

2022-07-26 08:10 UTC, merged

2022-07-26 08:11 UTC, innobead commented
@derekbit Please help backport to 1.3.x and 1.2.x. Thanks.